Update to newer gcl based on fedora package.
The package is not building, but the previous package was in a
worse state. Failure error message is:
Error: Value stack overflow.
It is possible to play with the build and get an error about
unknown relocation 9, that is R_X86_64_GOTPCREL.